default_scope = 'mmaction'

model = dict(
    type='RecognizerViTSkeleton',
    data_preprocessor=dict(
        type='MultiModalDataPreprocessor',
        preprocessors=dict(
            rgb=dict(
                type='ActionDataPreprocessor',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True,
                format_shape='NCTHW'),
            skeleton=dict(
                type='ActionDataPreprocessor',
                to_float32=True,
                format_shape='NCTHW'))),
    vision_backbone=dict(
        type='VisionTransformer',
        img_size=224,
        patch_size=16,
        embed_dims=384,
        depth=12,
        num_heads=6,
        mlp_ratio=4,
        qkv_bias=True,
        num_frames=16,
        tubelet_size=2,
        drop_rate=0.1,
        attn_drop_rate=0.0,
        drop_path_rate=0.1),
    skeleton_backbone=dict(
        type='SkeletonTransformer',
        num_joints=25,
        num_feats=3,
        embed_dims=384,
        depth=4,
        num_heads=6,
        mlp_ratio=4.0,
        dropout=0.1,
        max_position_embeddings=300),
    cls_head=dict(
        type='TransformerFusionHead',
        num_classes=400,
        vision_channels=384,
        skeleton_channels=384,
        fusion_mode='concat',
        dropout=0.5))
